# version: '3.8'

# services:
#   # Service untuk PostgreSQL
#   db:
#     image: postgres:latest
#     container_name: portfolio_db
#     environment:
#       POSTGRES_USER: admin
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: portfolio_db
#     ports:
#       - "5432:5432"
#     volumes:
#       - ./data/db:/var/lib/postgresql/data
#     networks:
#       - portfolio_network

#   # Service untuk Next.js
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: portfolio_app
#     ports:
#       - "3000:3000"
#     environment:
#       DATABASE_URL: postgres://admin:password@db:5432/portfolio_db
#     depends_on:
#       - db
#     networks:
#       - portfolio_network
#     volumes:
#       - ./prisma:/app/prisma

# networks:
#   portfolio_network:
#     driver: bridge


services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      # - /app/node_modules  # agar node_modules di host tidak bentrok
    environment:
      - NODE_ENV=development
      - JWT_SECRET=supersecretkey123
    depends_on:
      - db

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: portfolio_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
