# Dockerfile.dev

FROM node:18-alpine

WORKDIR /app

# Install deps dulu
COPY package*.json ./
RUN npm install

# Lalu copy semua file
COPY . .

# Generate Prisma client di lokasi benar
RUN npx prisma generate

EXPOSE 3000

CMD sh -c "npx prisma generate && npx prisma migrate deploy && npm run dev"
