# Dockerfile.dev

FROM node:18-alpine

WORKDIR /app

# Copy only package files first for better caching
COPY package*.json ./
RUN npm install

# Copy all source code
COPY . .

# Expose port Next.js
EXPOSE 3000

# Jalankan prisma generate dan migrate setiap container naik
CMD sh -c "npx prisma generate && npx prisma migrate deploy && npm run dev"
